export {default as Header} from './Header'
export {default as Main} from './Main'
export {default as Password} from './Password'
export {default as Alert} from './Alert'
export {default as Footer} from './Footer'